### ISSUE TITLE
TypeError: Cannot read property 'origin' of undefined

### ISSUE THREAD

**Issue by mikestaub** [redux-offline/redux-offline#308]
### Are you using `offline()` or `createOffline()` API?
offline()

### Store config
I am using the default config.

I am using a basic configuration following the README verbatim. When I try to include my store.js file I get this error. This only happens when testing with jest. Any ideas?

Here is my stack trace:
```

/Users/mike/code/myapp/node_modules/jsdom/lib/jsdom/browser/Window.js:280
if (this._document.origin === "null") {
                   ^

TypeError: Cannot read property 'origin' of undefined
at Window.get localStorage [as localStorage] (/Users/mike/code/myapp/node_modules/jsdom/lib/jsdom/browser/Window.js:280:26)
at _hasStorage (/Users/mike/code/myapp/node_modules/redux-persist/lib/defaults/asyncLocalStorage.js:89:101)
at hasLocalStorage (/Users/mike/code/myapp/node_modules/redux-persist/lib/defaults/asyncLocalStorage.js:107:10)
at getStorage (/Users/mike/code/myapp/node_modules/redux-persist/lib/defaults/asyncLocalStorage.js:116:12)
at Object.<anonymous>.exports.default (/Users/mike/code/myapp/node_modules/redux-persist/lib/defaults/asyncLocalStorage.js:8:17)
at getStoredState (/Users/mike/code/myapp/node_modules/redux-persist/lib/getStoredState.js:18:67)
at Immediate.<anonymous> (/Users/mike/code/myapp/node_modules/redux-persist/lib/persistStore.js:43:36)
at runCallback (timers.js:706:11)
at tryOnImmediate (timers.js:676:5)
at processImmediate (timers.js:658:5)
```

### Are you reporting a bug?

Yes, I followed the guide and all my deps are up to date.

**Comment by mikestaub** [comment]
After some deeper debugging I discovered that it was the react-scripts package. After changing from v2 -> v1 I no longer get that error. I'm not sure why.

**Comment by sorodrigo** [comment]
I think create-react-app v2 includes js-dom by default. Maybe you can use the v2 and pass a flag no to include it?

**Comment by mikestaub** [comment]
I was able to use a setupTest.js file to make the error above become just a warning using v2. I defined a mock localStorage class in that file.

https://facebook.github.io/create-react-app/docs/running-tests#src-setuptestsjs

**Comment by piranna** [comment]
@mikestaub, can you provide more details how did you fix it? I'm facing the same problem testing a library that internally makes use of `redux-offline`...

**Comment by mikestaub** [comment]
I created a file at `<root>/src/setupTests.js` and pasted this in it:

```
class LocalStorageMock {
  constructor() {
    this.store = {};
  }
  clear() {
    this.store = {};
  }
  getItem(key) {
    return this.store[key] || null;
  }
  setItem(key, value) {
    this.store[key] = value.toString();
  }
  removeItem(key) {
    delete this.store[key];
  }
}

const localStorage = new LocalStorageMock();

// jest test environment expects these to exist
window.localStorage = localStorage
```

**Comment by piranna** [comment]
@mikestaub, I have tried with both your implementation and the one at https://github.com/clarkbw/jest-localstorage-mock and in both cases I still get the error, with the difference that by using these ones instead of the `jsdom` default one, I get a `redux-persist localStorage test failed, persistence will be disabled` warning at `node_modules/redux-persist/lib/defaults/asyncLocalStorage.js:100` and continue executing the tests instead of a crash. It's a bit strange, because debuging that file it still has the `TypeError: Cannot read property 'origin' of undefined`, so it doesn't makes use of the mocks but instead is still using the `jsdom` one...

What alternatives does we have besides splitly disabling persistence? And how can we do that, too?

**Comment by calumpeak** [comment]
Just leaving my two cents here - You shouldn't need to test redux-offline's behaviour, should be safe just to stub it out with return values etc.

If you want to explicitly mock as above, have you checked that setupTests runs after jsDom is initialised? 
Generally I prefer to be explicit, e.g.

```javascript
let storage;
beforeEach(() => {
  storage = window.localStorage();
  window.localStorage = new LocalStorageMock();
});

afterEach(() => {
 window.localStorage = storage
});

test('my test', () => {})
```

**Comment by piranna** [comment]
@echoes221, I have check with your code sample and it works, and yes, with `setupFilesAfterEnv` worked but with `setupFiles` didn't, don't know why it didn't with setting it globally in any of the cases... Anyway, you are right it makes more sense to initialize it in each test...

**Comment by piranna** [comment]
Err... no, wrong success, it still shows the warning:

```
  console.warn node_modules/redux-persist/lib/defaults/asyncLocalStorage.js:100
    redux-persist localStorage test failed, persistence will be disabled.
```

At least tests are passing, and I'm not interested on persistence for the tests at all by the moment (maybe in the future I'll add support to set a custom `redux-persist` storage and in that case I could test with an in-memory one), but it's a bit annoying to find this warning... :-/ What can we do to prevent it?

**Comment by calumpeak** [comment]
As a rule of thumb, you should try to avoid running test setups where things are not needed (e.g. all of your tests do not need that stub), I prefer to create a manual mock util and import where needed and do the setup/teardown. I do the same with `enzymeAdapter` as not every test is running JSX.

At what level are you testing your application where it's diving into redux-persist/redux-offline? If you're testing your store, you shouldn't care about middlewares as we test our own modules. I normally do something like this:

```javascript
jest.mock("@redux-offline/redux-offline", () => ({
  offline: config => store => next => action => next(action)
}));


// Require test module here to ensure deps are mocked
```
That way you remove redux-offline completely from your dependencies when testing and just create a base middleware flow that won't break your application.

**Comment by Deepanshu088** [comment]
@sorodrigo  I think the title of the error should be -
"redux-persist localStorage test failed, persistence will be disabled"
I am facing the same issue, anyone had any success?
