### ISSUE TITLE
reduxOffline.createOffline is not a function & Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by nikoremi97** [redux-offline/redux-offline#321]
### Are you using `offline()` or `createOffline()` API?
*createOffline()*
but I also tried with *offline()*

I throws several errors trying to createStore. 
I've already see https://github.com/redux-offline/redux-offline/issues/224#issue-321725013 but did not get my problem solved

### Store config
Please paste your config below.
```
"dependencies": {
    "@babel/core": "7.4.4",
    "@babel/plugin-transform-runtime": "7.4.4",
    "@babel/runtime": "7.4.4",
    "@redux-offline/redux-offline": "2.5.1",
    "@types/": "redux-offline/redux-offline",
    "@types/enzyme": "3.1.15",
    "@types/prop-types": "15.5.8",
    "@types/react-dom": "16.0.11",
    "@types/react-native": "0.57.32",
    "@types/react-native-share": "1.1.0",
    "@types/react-native-vector-icons": "4.6.4",
    "@types/react-navigation": "3.0.1",
    "@types/react-redux": "6.0.6",
    "@types/redux": "3.6.0",
    "react": "16.6.3",
    "react-native": "0.57.8",
    .
    .
    .
    "react-navigation": "3.0.9",
    "react-navigation-redux-helpers": "2.0.9",
    "react-redux": "5.0.7",
    "redux": "4.0.1",
    "redux-thunk": "2.3.0"
  },
  "devDependencies": {
    "@types/detox": "9.0.3",
    "@types/jasmine": "3.3.8",
    "@types/jest": "23.3.13",
    "@types/redux-mock-store": "1.0.0",
    "@types/sinon": "7.0.4",
    "await-to-js": "2.1.1",
    "awesome-typescript-loader": "5.2.1",
    "babel-jest": "24.0.0",
    "babel-preset-react-native": "5.0.2",
    "enzyme": "3.3.0",
    "enzyme-adapter-react-16": "1.0.2",
    "jest": "24.8.0",
    "metro-react-native-babel-preset": "0.51.1",
    "react-dom": "16.7.0",
    "redux-mock-store": "1.5.3",
    "request": "2.88.0",
    "sinon": "7.2.3",
    "source-map-loader": "0.2.4",
    "tslint": "5.12.1",
    "typescript": "3.4.5"
```

**createOffline()**
```
import { applyMiddleware, createStore, compose } from 'redux';
import thunk from 'redux-thunk';
import { createOffline, offline } from '@redux-offline/redux-offline';
import { Config } from '@redux-offline/redux-offline/lib/types';
import offlineConfig from '@redux-offline/redux-offline/lib/defaults';
const offlineEnhancer = createOffline(config);

export default function configureStore() {
  const store = createStore(
    offlineEnhancer.enhanceReducer(rootReducer), // rootReducer is a combineReducers product
    compose(
      applyMiddleware(thunk, offlineEnhancer.middleware),
      offlineEnhancer.enhanceStore(rootReducer),
    )
  );
  return store;
}
```

### Offline config

Are you using a custom configuration? If you are please paste your config below.
```

const config: Config = {
  ...offlineConfig,
  persistOptions: {
    whitelist: ['item']
  },
};

```
### When test is running...
I'm importing *createOffline* like this `import { createOffline } from '@redux-offline/redux-offline';`
when the store is created I get this error:

```
 TypeError: (0 , _reduxOffline.createOffline) is not a function

      25 |     )
      26 |   );
    > 27 |   return store;
```

**Using offline**
If i create store using *offline()*, i do it in this way:

```
export default function configureStore() {
  const store = createStore(
    rootReducer,
    compose(
           applyMiddleware(thunk), 
            offline(config))
  );
  return store;
}
```
Get this error writing code:
`Type instantiation is excessively deep and possibly infinite`
And get this error running test:
```
 TypeError: b.apply is not a function

      25 | //     )
      26 | //   );
    > 27 | //   return store;
         |                             ^
      28 | // }
      29 | export default function configureStore() {
      30 |   const store = createStore(

      at node_modules/redux/lib/redux.js:579:18
      at createStore (node_modules/redux/lib/redux.js:85:12)
```

**Comment by calumpeak** [comment]
As per the docs. `enhanceStore` must come before `applyMiddleware` in `compose`: https://github.com/redux-offline/redux-offline/blob/develop/docs/api/createOffline.md

Can you see if that helps to fix the issue please.

**Comment by nikoremi97** [comment]
I changed the order to 
```
export default function configureStore() {
  const offlineEnhancer = createOffline(config);
  const store = createStore(
    offlineEnhancer.enhanceReducer(rootReducer),
    compose(
      offlineEnhancer.enhanceStore(rootReducer),
      applyMiddleware(thunk, offlineEnhancer.middleware)
    )
  );
  return store;
}

```

But it keeps giving me this error:
```
● Test suite failed to run

    TypeError: (0 , _reduxOffline.createOffline) is not a function

      25 |       offlineEnhancer.enhanceStore(rootReducer),
      26 |       applyMiddleware(thunk, offlineEnhancer.middleware)
    > 27 |     )
         |      ^
      28 |   );
      29 |   return store;
      30 | }
```
